site_name: NSITBIM - dsplus - documentation
site_url: https://nsitbim.gitlab.io/satellites/dsplus/documentation
site_dir: public
nav:
    - Introduction: index.md
    - Quickstart: quickstart.md
    - Configuration:
        - config/confFile.md
        - config/env.md
        - config/git.md
    - Tutoriaux:
        - tutos/designerIntegration.md
        - tutos/automatePlugins.md
        - tutos/openQualityReport.md
        - tutos/versionTracking.md
    - Fonctionalités: 
        - features/projects.md
        - features/list.md
        - features/get.md
        - features/init.md
        - features/status.md
        - features/package.md
        - features/manifest.md
        - features/deploy.md
        - features/quality.md
        - features/coverage.md
        - features/check.md
        - features/configure.md
        - features/current.md
        - features/encrypt.md
        - features/properties.md
        - features/publish.md


theme: material
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html